/**
 * frontend/src/utils/indications.js — Clinical Indication & Medical Condition Resolver
 * ─────────────────────────────────────────────────────────────────────────────
 * Resolves the primary medical condition, illness, symptom, or therapeutic purpose
 * ("What this medicine is used for") across 500+ Indian & international formulations.
 */

// ─── Curated Medical Indications Formulary (691+ Entries) ────────────────────
export const MEDICINE_INDICATIONS = {
  'xyzal': 'Allergic Rhinitis, Sneezing, Runny Nose, Watery Eyes & Allergic Asthma',
  'xyzal m': 'Allergic Rhinitis, Sneezing, Runny Nose, Watery Eyes & Allergic Asthma',
  'montair lc': 'Allergic Rhinitis, Hay Fever, Bronchial Asthma & Nasal Congestion',
  'montek lc': 'Allergic Rhinitis, Sneezing, Runny Nose & Allergic Asthma',
  'telekast l': 'Asthma Prophylaxis, Seasonal Allergies & Allergic Rhinitis',
  'levocetirizine': 'Allergic Rhinitis, Sneezing, Runny Nose, Watery Eyes & Itching',
  'montelukast': 'Asthma Maintenance, Bronchospasm & Allergic Rhinitis',
  'cetirizine': 'Allergy, Sneezing, Runny Nose, Hives & Watery Eyes',
  'zyrtec': 'Seasonal Allergic Rhinitis & Chronic Urticaria (Hives)',
  'allegra': 'Seasonal Allergies, Allergic Rhinitis & Chronic Urticaria (Hives)',
  'fexofenadine': 'Non-Drowsy Allergy Relief, Sneezing & Itchy Skin Rash',
  'loratadine': 'Non-Sedating Allergy Relief, Hives & Allergic Rhinitis',
  'claritin': 'Seasonal Allergies, Pollen Allergy & Skin Itchiness',
  'desloratadine': 'Allergic Rhinitis & Chronic Idiopathic Urticaria',
  'clarinex': 'Relief from Nasal & Non-Nasal Seasonal Allergic Symptoms',
  'bilastine': 'Allergic Rhinoconjunctivitis & Urticaria',
  'bilaxten': 'Allergic Rhinitis & Itchy Skin Rash',
  'cheston cold': 'Common Cold, Nasal Congestion, Runny Nose & Fever',
  'sinarest': 'Cold, Sinus Congestion, Headache & Low-Grade Fever',
  'wikoryl': 'Common Cold, Nasal Decongestion, Headache & Body Aches',
  'solvin cold': 'Sneezing, Nasal Blockage, Sinus Congestion & Cold Fever',
  'ascoril': 'Productive Cough, Chest Congestion & Bronchial Spasm',
  'ascoril ls': 'Productive Mucus Cough, Bronchitis & Chest Congestion',
  'benadryl': 'Cough Relief, Throat Soothing & Nighttime Cough Suppression',
  'alex': 'Dry Irritating Cough & Throat Tickling Relief',
  'grilinctus': 'Dry Allergic Cough & Irritating Throat Relief',
  'corex': 'Cough Suppression & Upper Respiratory Congestion',
  'phensedyl': 'Severe Dry Cough & Bronchial Irritation Relief',
  'asthalin': 'Acute Asthma Attack, Wheezing & Bronchospasm',
  'salbutamol': 'Acute Bronchospasm, Asthma & COPD Bronchodilation',
  'albuterol': 'Bronchospasm, Wheezing & Exercise-Induced Asthma',
  'ventolin': 'Rapid Bronchospasm Relief in Asthma & COPD',
  'deriphyllin': 'Chronic Asthma, Wheezing & COPD Airway Clearance',
  'theophylline': 'Chronic Asthma Maintenance & COPD Bronchodilation',
  'foracort': 'Chronic Asthma Maintenance & COPD Symptom Prevention',
  'foracort 200': 'Asthma & COPD Daily Anti-inflammatory Maintenance',
  'foracort 400': 'Moderate to Severe Persistent Asthma & COPD Maintenance',
  'seroflo': 'Persistent Asthma & COPD Airflow Obstruction Prevention',
  'seroflo 250': 'Daily Maintenance for Chronic Asthma & Bronchospasm',
  'budecort': 'Asthma Airway Inflammation & Chronic Bronchitis',
  'budesonide': 'Airway Inflammation, Asthma & Chronic Lung Inflammation',
  'pulmicort': 'Inhaled Corticosteroid for Persistent Asthma Control',
  'fluticasone': 'Allergic Rhinitis (Nasal Spray) & Asthma Airway Inflammation',
  'flonase': 'Nasal Allergy Relief, Congestion, Sneezing & Itchy Nose',
  'mometasone': 'Nasal Polyps, Chronic Allergic Rhinitis & Airway Inflammation',
  'nasonex': 'Seasonal & Perennial Allergic Rhinitis Nasal Symptoms',
  'ipratropium': 'Bronchospasm in COPD, Emphysema & Rhinorrhea',
  'atrovent': 'COPD Bronchodilation & Chronic Bronchitis Relief',
  'tiotropium': 'Long-term COPD Maintenance & Severe Asthma Bronchodilation',
  'spiriva': 'Once-Daily Maintenance Therapy for COPD & Emphysema',
  'duolin': 'Acute Severe Asthma & COPD Bronchospasm (Dual Bronchodilator)',
  'levosalbutamol': 'Bronchospasm Relief with Reduced Tachycardia',
  'ambroxol': 'Mucus Thinning & Productive Wet Cough Clearance',
  'guaifenesin': 'Chest Congestion & Mucus Loosening Expectorant',
  'mucinex': 'Excess Bronchial Mucus & Chest Congestion Relief',
  'acetylcysteine': 'Thick Bronchial Mucus Dissolution & Acetaminophen Overdose',
  'mucomix': 'Respiratory Mucus Breakdown & Lung Airway Clearance',
  'dextromethorphan': 'Dry Non-Productive Cough Reflex Suppression',
  'pseudoephedrine': 'Severe Nasal Congestion & Sinus Pressure Relief',
  'sudafed': 'Nasal & Sinus Congestion from Colds & Allergies',
  'otrivin': 'Nasal Decongestion & Acute Stuffy Nose Relief',
  'oxymetazoline': 'Rapid Nasal Congestion Relief for Head Colds & Sinusitis',
  'naxdom': 'Acute Migraine Headache, Throbbing Headache with Nausea & Vomiting',
  'naxdom 500': 'Acute Migraine Headache, Throbbing Headache with Nausea & Vomiting',
  'naxdom 250': 'Acute Migraine Headache, Throbbing Headache with Nausea & Vomiting',
  'migranil': 'Migraine Attacks & Vascular Headaches',
  'sumatriptan': 'Acute Migraine Headache with or without Aura',
  'imitrex': 'Acute Migraine Attacks & Cluster Headaches',
  'zolmitriptan': 'Acute Migraine Headache Relief',
  'rizatriptan': 'Fast-Acting Migraine Headache Relief',
  'vasograin': 'Vascular Headaches & Recurring Migraines',
  'dolo': 'Fever, Headache, Body Aches & Mild to Moderate Pain Relief',
  'dolo 650': 'Fever, Headache, Body Aches & Mild to Moderate Pain Relief',
  'calpol': 'Fever, Headache & Mild to Moderate Pain Relief',
  'calpol 650': 'High Fever, Headache & Post-Vaccination Fever',
  'crocin': 'Fever, Body Ache, Toothache & Mild Headache Relief',
  'crocin 650': 'Fever, Muscle Aches & Headache Relief',
  'paracetamol': 'Fever Reduction, Headache & Mild to Moderate Pain Relief',
  'acetaminophen': 'Fever Reduction, Headache & General Pain Relief',
  'combiflam': 'Severe Musculoskeletal Pain, Joint Inflammation & Fever',
  'flexon': 'Musculoskeletal Pain, Sprains, Dental Pain & Fever',
  'sumo': 'Severe Body Ache, Joint Pain, Sprain & High Fever',
  'ibuprofen': 'Inflammatory Pain, Dental Ache, Muscle Sprains & Fever',
  'brufen': 'Inflammation, Muscle Pain & Dental Ache',
  'advil': 'Headache, Toothache, Muscle Sprains, Backache & Fever',
  'motrin': 'Minor Aches, Pain of Arthritis, Dysmenorrhea & Fever',
  'voveran': 'Severe Joint Pain, Osteoarthritis & Musculoskeletal Inflammation',
  'voveran sr': 'Chronic Osteoarthritis, Rheumatoid Pain & Spinal Spondylitis',
  'diclofenac': 'Joint Pain, Sprain, Arthritis & Post-Operative Inflammation',
  'voltaren': 'Osteoarthritis Pain, Joint Stiffness & Inflammatory Aches',
  'naproxen': 'Migraine, Arthritis, Gout & Musculoskeletal Pain',
  'aleve': 'All-Day Relief for Arthritis, Backache & Muscle Strain',
  'meftal': 'Menstrual Cramps, Heavy Bleeding Pain & Post-Operative Aches',
  'meftal spas': 'Abdominal Cramping, Menstrual Pain & Intestinal Spasms',
  'mefenamic acid': 'Menstrual Pain, Spasms & Mild to Moderate Inflammatory Pain',
  'ultracet': 'Moderate to Severe Acute Pain Relief',
  'tramadol': 'Moderate to Severe Pain Management',
  'ultram': 'Moderate to Moderately Severe Chronic Pain',
  'zerodol': 'Osteoarthritis, Rheumatoid Arthritis & Ankylosing Spondylitis',
  'zerodol p': 'Acute Joint Pain, Back Pain & Dental Pain with Fever',
  'zerodol sp': 'Severe Traumatic Swelling, Post-Surgery Edema & Joint Pain',
  'hifenac': 'Arthritis Joint Pain, Spondylitis & Musculoskeletal Aches',
  'aceclofenac': 'Pain & Inflammation in Osteoarthritis & Ankylosing Spondylitis',
  'etoricoxib': 'Acute Gout, Severe Osteoarthritis & Ankylosing Spondylitis Pain',
  'arcoxia': 'Joint Pain, Rheumatoid Arthritis & Acute Gouty Arthritis',
  'etoshine': 'Severe Arthritis Joint Inflammation & Post-Surgical Pain',
  'celecoxib': 'Osteoarthritis, Rheumatoid Arthritis & Acute Pain Relief',
  'celebrex': 'Arthritis Joint Pain & Ankylosing Spondylitis (GI-Gentle)',
  'meloxicam': 'Osteoarthritis & Rheumatoid Arthritis Joint Stiffness',
  'mobic': 'Relief of Signs & Symptoms of Osteoarthritis & Rheumatoid Arthritis',
  'piroxicam': 'Chronic Osteoarthritis & Rheumatoid Arthritis Inflammation',
  'indomethacin': 'Acute Gouty Arthritis, Bursitis & Severe Tendonitis',
  'ketorolac': 'Short-term Management of Moderately Severe Acute Pain',
  'toradol': 'Post-Surgical Acute Moderate-to-Severe Pain Relief',
  'chymoral forte': 'Post-Traumatic Swelling, Surgical Edema & Tissue Inflammation',
  'trypsin chymotrypsin': 'Wound Edema, Hematoma & Post-Operative Inflammation',
  'serratiopeptidase': 'Reduction of Tissue Swelling, Edema & Traumatic Hematoma',
  'colchicine': 'Acute Gout Attack Relief & Familial Mediterranean Fever',
  'tofacitinib': 'Rheumatoid Arthritis, Psoriatic Arthritis & Ulcerative Colitis',
  'xeljanz': 'Active Rheumatoid Arthritis, Psoriatic Arthritis & Ulcerative Colitis',
  'tfct-nib': 'Rheumatoid Arthritis, Psoriatic Arthritis & Ulcerative Colitis',
  'tfct-nib 5 mg': 'Rheumatoid Arthritis, Psoriatic Arthritis & Ulcerative Colitis',
  'upadacitinib': 'Rheumatoid Arthritis, Atopic Dermatitis & Ulcerative Colitis',
  'rinvoq': 'Rheumatoid Arthritis, Crohn’s Disease & Atopic Dermatitis',
  'baricitinib': 'Rheumatoid Arthritis, Alopecia Areata & Severe Atopic Dermatitis',
  'olumiant': 'Moderate to Severe Active Rheumatoid Arthritis',
  'methotrexate': 'Rheumatoid Arthritis, Severe Psoriasis & Autoimmune Remission',
  'folitrax': 'Rheumatoid Arthritis & Severe Psoriatic Plaques',
  'trexall': 'Rheumatoid Arthritis, Psoriasis & Neoplastic Conditions',
  'hydroxychloroquine': 'Systemic Lupus Erythematosus (SLE) & Rheumatoid Arthritis',
  'hcqs': 'Systemic Lupus (SLE) & Autoimmune Joint Inflammation',
  'plaquenil': 'Systemic Lupus Erythematosus & Rheumatoid Arthritis Disease Modification',
  'chloroquine': 'Malaria Treatment, Amebiasis & Extraintestinal Amebiasis',
  'leflunomide': 'Active Rheumatoid Arthritis Joint Damage Retardation',
  'arava': 'Reduction of Joint Damage in Active Rheumatoid Arthritis',
  'sulfasalazine': 'Ulcerative Colitis & Seronegative Spondylarthropathy',
  'saaz': 'Ulcerative Colitis, Crohn’s Colitis & Peripheral Rheumatoid Arthritis',
  'azathioprine': 'Kidney Transplant Rejection Prophylaxis & Severe Autoimmune Disease',
  'imuran': 'Organ Transplant Immunosuppression & Autoimmune Hepatitis',
  'mycophenolate': 'Renal / Cardiac Transplant Rejection Prophylaxis & Lupus Nephritis',
  'cellcept': 'Organ Rejection Prophylaxis in Kidney, Heart, or Liver Transplants',
  'myfortic': 'Prophylaxis of Organ Rejection in Adult Kidney Transplants',
  'tacrolimus': 'Organ Transplant Rejection Prophylaxis & Atopic Eczema',
  'prograf': 'Liver, Kidney, and Heart Transplant Rejection Prevention',
  'cyclosporine': 'Organ Transplant Rejection Prophylaxis & Severe Psoriasis',
  'neoral': 'Immunosuppression in Solid Organ Transplantation & Severe RA',
  'sandimmune': 'Prophylaxis of Organ Rejection in Kidney, Liver, and Heart Allografts',
  'prednisolone': 'Severe Allergic Reactions, Autoimmune Flare-ups & Inflammation',
  'wysolone': 'Severe Inflammatory Flare-ups, Allergies & Autoimmune Suppression',
  'prednisone': 'Autoimmune Disorders, Severe Inflammation & Allergic Flare-ups',
  'deltasone': 'Endocrine Disorders, Severe Arthritis & Allergic States',
  'dexamethasone': 'Severe Allergic Flare-ups, Cerebral Edema & Shock States',
  'decadron': 'Inflammatory Conditions, Cerebral Edema & Chemotherapy Nausea',
  'methylprednisolone': 'Acute Spinal Injury, Multiple Sclerosis Exacerbation & Severe Inflammation',
  'medrol': 'Rheumatoid Arthritis, Systemic Lupus & Severe Allergic Reactions',
  'defcort': 'Severe Inflammation, Joint Swelling & Allergic Disorders',
  'deflazacort': 'Anti-inflammatory & Immunosuppressive Glucocorticoid Therapy',
  'adalimumab': 'Rheumatoid Arthritis, Ankylosing Spondylitis, Crohn’s & Psoriasis',
  'humira': 'Tumor Necrosis Factor (TNF) Blocker for Autoimmune Diseases',
  'etanercept': 'Rheumatoid Arthritis, Polyarticular JIA & Psoriatic Arthritis',
  'enbrel': 'Anti-TNF Biologic for Moderate to Severe Rheumatoid Arthritis',
  'amlodipine': 'High Blood Pressure (Hypertension) & Angina (Chest Pain)',
  'norvasc': 'High Blood Pressure (Hypertension) & Coronary Artery Disease',
  'stamlo': 'High Blood Pressure (Hypertension) & Chronic Stable Angina',
  'amlong': 'High Blood Pressure (Hypertension) & Angina Relief',
  'amlovas': 'Hypertension & Prevention of Chronic Angina Episodes',
  'cilnidipine': 'Hypertension & Renal Microcirculation Protection',
  'cilacar': 'High Blood Pressure with Kidney-Protective Vasodilation',
  'nifedipine': 'Hypertension, Vasospastic Angina & Raynaud Phenomenon',
  'procardia': 'Chronic Stable Angina & Vasospastic Angina',
  'adalat': 'Hypertension & Angina Pectoris Management',
  'felodipine': 'High Blood Pressure Management (Vascular-Selective)',
  'plendil': 'Hypertension Treatment Alone or with Other Antihypertensives',
  'diltiazem': 'Hypertension, Chronic Angina & Atrial Fibrillation Rate Control',
  'cardizem': 'Angina Pectoris & High Blood Pressure Control',
  'verapamil': 'Hypertension, Angina & Supraventricular Tachycardia Control',
  'calan': 'Angina, Arrhythmias & Essential Hypertension',
  'telmisartan': 'High Blood Pressure & Stroke / Heart Attack Risk Reduction',
  'telma': 'High Blood Pressure (Hypertension) & Cardiovascular Risk Reduction',
  'telma h': 'Hypertension with Fluid Retention (Blood Pressure + Diuretic)',
  'telmikind': 'High Blood Pressure Management & Vascular Protection',
  'micardis': 'Hypertension & Cardiovascular Risk Reduction in High-Risk Patients',
  'losartan': 'High Blood Pressure & Diabetic Kidney Protection (Nephropathy)',
  'losar': 'High Blood Pressure & Diabetic Nephropathy',
  'cozaar': 'Hypertension & Nephropathy in Type 2 Diabetic Patients',
  'valsartan': 'High Blood Pressure, Heart Failure & Post-Myocardial Infarction',
  'diovan': 'Hypertension, Heart Failure & Post-Heart Attack Survival',
  'olmesartan': 'High Blood Pressure (Hypertension) Management',
  'benicar': 'High Blood Pressure (Hypertension) Reduction',
  'candesartan': 'High Blood Pressure & Heart Failure with Reduced Ejection Fraction',
  'atacand': 'Hypertension & Heart Failure NYHA Class II-IV',
  'irbesartan': 'Hypertension & Diabetic Nephropathy in Type 2 Diabetes',
  'avapro': 'High Blood Pressure & Renal Protection in Diabetics',
  'lisinopril': 'High Blood Pressure (Hypertension) & Heart Failure Management',
  'zestril': 'Hypertension, Heart Failure Adjunct & Post-MI Survival',
  'prinivil': 'High Blood Pressure & Congestive Heart Failure',
  'ramipril': 'High Blood Pressure, Heart Failure & Post-Heart Attack Survival',
  'cardace': 'High Blood Pressure & Cardiovascular Disease Prevention',
  'altace': 'Hypertension, Heart Failure & Stroke Risk Reduction',
  'enalapril': 'High Blood Pressure & Congestive Heart Failure',
  'vasotec': 'Hypertension, Symptomatic Heart Failure & Asymptomatic LV Dysfunction',
  'perindopril': 'Hypertension & Stable Coronary Artery Disease Risk Reduction',
  'coversyl': 'High Blood Pressure & Secondary Prevention in CAD',
  'atenolol': 'High Blood Pressure, Angina & Irregular Heart Rhythms',
  'tenormin': 'Hypertension, Angina Pectoris & Acute Myocardial Infarction',
  'metoprolol': 'High Blood Pressure, Angina, Heart Failure & Arrhythmia Control',
  'betaloc': 'High Blood Pressure & Post-Myocardial Infarction Protection',
  'toprol xl': 'Hypertension, Angina Pectoris & NYHA Class II/III Heart Failure',
  'lopressor': 'High Blood Pressure, Angina Pectoris & Post-Heart Attack Therapy',
  'nebivolol': 'Hypertension & Mild to Moderate Heart Failure',
  'bystolic': 'High Blood Pressure Management with Nitric Oxide Vasodilation',
  'bisoprolol': 'Chronic Heart Failure & High Blood Pressure Management',
  'concor': 'Hypertension & Chronic Stable Heart Failure',
  'zebeta': 'Essential Hypertension Blood Pressure Lowering',
  'carvedilol': 'Heart Failure, Post-Heart Attack Left Ventricular Dysfunction & Hypertension',
  'coreg': 'Mild to Severe Heart Failure & Hypertension',
  'cardivas': 'Hypertension & Dilated Cardiomyopathy / Heart Failure',
  'propranolol': 'High Blood Pressure, Tremors, Migraine Prevention & Angina',
  'inderal': 'Hypertension, Angina, Essential Tremor & Migraine Prophylaxis',
  'ciptab': 'Performance Anxiety, Palpitations & High Blood Pressure',
  'furosemide': 'Severe Fluid Retention (Edema) in Heart Failure, Liver Cirrhosis & Kidney Disease',
  'lasix': 'Edema from Heart Failure, Hepatic Cirrhosis, Renal Disease & Hypertension',
  'torsemide': 'Edema Associated with Congestive Heart Failure & Hypertension',
  'dytor': 'Edema Associated with Heart Failure, Kidney Disease & Hypertension',
  'demadex': 'Fluid Overload in Heart Failure, Chronic Kidney Failure & Cirrhosis',
  'bumetanide': 'Potent Diuretic for Refractory Edema in Heart Failure',
  'hydrochlorothiazide': 'High Blood Pressure & Mild Fluid Retention',
  'chlorthalidone': 'Long-acting Diuretic for High Blood Pressure & Stroke Prevention',
  'hygroton': 'Hypertension & Fluid Retention in Congestive Heart Failure',
  'indapamide': 'High Blood Pressure Management with Minimal Metabolic Derangement',
  'spironolactone': 'Congestive Heart Failure, Resistant Hypertension, Edema & Hypokalemia',
  'aldactone': 'Heart Failure Mortality Reduction, Edema & Hyperaldosteronism',
  'eplerenone': 'Congestive Heart Failure Post-Heart Attack & Resistant Hypertension',
  'inspra': 'Improve Survival in Patients with Left Ventricular Systolic Dysfunction',
  'digoxin': 'Heart Failure & Atrial Fibrillation Heart Rate Control',
  'lanoxin': 'Chronic Heart Failure & Rate Control in Atrial Fibrillation',
  'amiodarone': 'Life-Threatening Ventricular Arrhythmias & Atrial Fibrillation',
  'cordarone': 'Refractory Ventricular Arrhythmias & Cardioversion Maintenance',
  'flecainide': 'Prevention of Paroxysmal Atrial Fibrillation & SVT',
  'sorbitrate': 'Acute Angina Pectoris (Chest Pain Relief)',
  'monit': 'Prevention of Chronic Angina (Chest Pain Attacks)',
  'nitroglycerin': 'Immediate Relief from Angina / Ischemic Chest Pain',
  'nitrostat': 'Sublingual Relief of Acute Angina Pectoris Attacks',
  'warfarin': 'Blood Clot Prevention (Deep Vein Thrombosis, PE) & Stroke Risk in AFib',
  'coumadin': 'Blood Clot Treatment & Embolism Prevention in Heart Valve / AFib',
  'aspirin': 'Heart Attack & Stroke Prevention, Antiplatelet Protection & Pain Relief',
  'ecosprin': 'Low-Dose Blood Thinner for Heart Attack & Stroke Prevention',
  'ecosprin 75': 'Cardioprotective Low-Dose Antiplatelet for Clot Prevention',
  'ecosprin 150': 'Secondary Prevention of Acute Coronary Events & Stroke',
  'clopidogrel': 'Prevention of Recurrent Stroke, Heart Attack & Arterial Stents',
  'plavix': 'Atherothrombosis Prevention & Post-Coronary Stent Anticoagulation',
  'clopilet': 'Blood Thinner & Clot Prevention in Stented Coronary Arteries',
  'clopivas': 'Prevention of Atherosclerotic Thrombotic Events',
  'prasugrel': 'Prevention of Thrombotic Events in Acute Coronary Syndrome with PCI',
  'effient': 'Reduction of Stent Thrombosis in Percutaneous Coronary Intervention',
  'ticagrelor': 'Heart Attack & Stent Clot Prevention in Acute Coronary Syndrome',
  'brilinta': 'Prevention of Cardiovascular Death & Myocardial Infarction in ACS',
  'rivaroxaban': 'Prevention of Deep Vein Thrombosis (DVT), Pulmonary Embolism & Stroke',
  'xarelto': 'DVT / PE Treatment & Stroke Prevention in Non-Valvular AFib',
  'apixaban': 'Non-Valvular AFib Stroke Prevention & Venous Thromboembolism Treatment',
  'eliquis': 'Blood Clot & Stroke Prevention in Atrial Fibrillation',
  'dabigatran': 'Direct Thrombin Inhibition for Blood Clot & Stroke Prevention',
  'pradaxa': 'DVT, Pulmonary Embolism & Non-Valvular AFib Thromboembolism',
  'edoxaban': 'Stroke Prevention in Non-Valvular AFib & Treatment of DVT/PE',
  'savaysa': 'Once-Daily Oral Anticoagulant for Stroke Risk Reduction',
  'heparin': 'Immediate Anticoagulation for Acute Thrombosis, PE & Angioplasty',
  'enoxaparin': 'Deep Vein Thrombosis Prophylaxis & Acute Coronary Syndrome',
  'lovenox': 'Prevention & Treatment of Deep Vein Thrombosis & Pulmonary Embolism',
  'dalteparin': 'Low Molecular Weight Heparin for VTE Prophylaxis & Cancer Thrombosis',
  'fondaparinux': 'Deep Vein Thrombosis Prophylaxis in Orthopedic Surgery & PE',
  'arixtra': 'Synthetic Factor Xa Inhibitor for Acute Thrombosis',
  'dipyridamole': 'Secondary Stroke Prevention & Pharmacologic Stress Testing',
  'persantine': 'Adjunct to Anticoagulants for Mechanical Heart Valves',
  'atorvastatin': 'High Cholesterol (Hyperlipidemia) & Cardiovascular Disease Prevention',
  'atorva': 'Lowering LDL Bad Cholesterol & Heart Attack Prevention',
  'lipitor': 'High Cholesterol & Arterial Plaque Reduction',
  'atorlip': 'Reduction of High Blood Cholesterol & Triglycerides',
  'rosuvastatin': 'Lowering LDL Bad Cholesterol & Atherosclerosis Prevention',
  'rozavel': 'Lowering Elevated Cholesterol & Triglyceride Blood Levels',
  'crestor': 'High Cholesterol Management & Plaque Buildup Retardation',
  'rosuvas': 'Elevated Lipid Levels & Coronary Artery Disease Prevention',
  'simvastatin': 'High Cholesterol & Cardiovascular Mortality Reduction',
  'zocor': 'Hypercholesterolemia & Coronary Heart Disease Survival',
  'pravastatin': 'Elevated Serum Cholesterol & Primary Prevention of CAD',
  'pravachol': 'Lipid Regulation with Minimal CYP3A4 Interactions',
  'lovastatin': 'Hyperlipidemia & Slowing Progression of Coronary Atherosclerosis',
  'pitavastatin': 'Potent Low-Dose Statin for Primary Hyperlipidemia',
  'livalo': 'Primary Hyperlipidemia & Mixed Dyslipidemia Treatment',
  'ezetimibe': 'Intestinal Cholesterol Absorption Blocker (Lowers LDL)',
  'zetia': 'Reduction of Elevated Total Cholesterol and LDL Alone or with Statins',
  'fenofibrate': 'Severe Hypertriglyceridemia & Mixed Dyslipidemia',
  'tricor': 'Significant Reduction of High Blood Triglycerides',
  'lipicard': 'Reduction of Elevated Serum Triglycerides & Pancreatitis Risk',
  'gemfibrozil': 'Severe Hypertriglyceridemia at Risk of Pancreatitis',
  'lopid': 'Triglyceride Lowering in Very High Blood Fat Conditions',
  'bempedoic acid': 'Non-Statin LDL Cholesterol Lowering',
  'nexletol': 'Adjunct Therapy for Heterozygous Familial Hypercholesterolemia',
  'evolocumab': 'PCSK9 Inhibitor for Dramatic LDL Reduction in High-Risk Patients',
  'repatha': 'Cardiovascular Event Reduction in Established Cardiovascular Disease',
  'metformin': 'Type 2 Diabetes Mellitus & Blood Glucose Regulation',
  'glycomet': 'Type 2 Diabetes Blood Sugar Control',
  'glycomet gp': 'Type 2 Diabetes Dual Therapy (Biguanide + Sulfonylurea)',
  'glycomet gp1': 'Type 2 Diabetes Blood Sugar Regulation',
  'glycomet gp2': 'Type 2 Diabetes Dual Glucose Lowering',
  'glucophage': 'Type 2 Diabetes Glycemic Control & Insulin Sensitization',
  'glimepiride': 'Type 2 Diabetes (Pancreatic Insulin Secretion Stimulation)',
  'amaryl': 'Type 2 Diabetes Mellitus Blood Sugar Regulation',
  'zoryl': 'Blood Sugar Lowering in Type 2 Diabetes',
  'gliclazide': 'Type 2 Diabetes Glycemic Control with Low Hypoglycemia Risk',
  'diamicron': 'Modified Release Type 2 Diabetes Blood Sugar Control',
  'glipizide': 'Type 2 Diabetes Mellitus Blood Sugar Lowering',
  'glucotrol': 'Type 2 Diabetes Control through Insulin Secretion',
  'sitagliptin': 'Type 2 Diabetes Glycemic Control (Incretin Enhancement)',
  'januvia': 'Type 2 Diabetes Blood Sugar Regulation without Weight Gain',
  'janumet': 'Type 2 Diabetes Dual Control (Sitagliptin + Metformin)',
  'vildagliptin': 'Type 2 Diabetes Incretin Enhancer for Glycemic Control',
  'galvus': 'Type 2 Diabetes Mellitus Postprandial & Fasting Glucose Control',
  'galvus met': 'Type 2 Diabetes Combined Therapy (Vildagliptin + Metformin)',
  'linagliptin': 'Type 2 Diabetes (Safe in Kidney Dysfunction)',
  'tradjenta': 'Type 2 Diabetes Control Requiring No Renal Dose Adjustments',
  'teneligliptin': 'Type 2 Diabetes Glycemic Control',
  'zita': 'Type 2 Diabetes Fasting & Post-Meal Sugar Regulation',
  'dapagliflozin': 'Type 2 Diabetes, Heart Failure & Chronic Kidney Disease Protection',
  'forxiga': 'Blood Glucose Control, Heart Failure & Kidney Protection',
  'farxiga': 'Type 2 Diabetes, HFrEF Mortality Reduction & CKD Progression Delay',
  'oxra': 'Type 2 Diabetes Glycemic Regulation & Renal Protection',
  'empagliflozin': 'Type 2 Diabetes, Heart Failure & Cardiovascular Mortality Reduction',
  'jardiance': 'Type 2 Diabetes Glucose Lowering & Heart Failure Protection',
  'canagliflozin': 'Type 2 Diabetes Glycemic Control & Diabetic Nephropathy Protection',
  'invokana': 'Lowering Blood Sugar in Type 2 Diabetes & Reducing Major CV Events',
  'pioglitazone': 'Type 2 Diabetes Insulin Sensitizer (PPAR-gamma Activation)',
  'actos': 'Improves Glycemic Control by Decreasing Insulin Resistance',
  'pioz': 'Type 2 Diabetes Management in Insulin-Resistant Patients',
  'acarbose': 'Postprandial Blood Glucose Spikes in Diabetes',
  'glucobay': 'Slowing Carbohydrate Digestion to Flatten After-Meal Glucose',
  'voglibose': 'Post-Meal High Blood Sugar (Postprandial Hyperglycemia)',
  'volibo': 'Postprandial Blood Sugar Spike Control in Diabetics',
  'semaglutide': 'Type 2 Diabetes Glycemic Control & Long-term Weight Management',
  'ozempic': 'Type 2 Diabetes Once-Weekly Glycemic Control & CV Risk Reduction',
  'rybelsus': 'Oral GLP-1 Receptor Agonist for Type 2 Diabetes Glucose Control',
  'wegovy': 'Chronic Weight Management in Obese or Overweight Adults',
  'liraglutide': 'Type 2 Diabetes Blood Sugar Control & Chronic Weight Management',
  'victoza': 'Daily GLP-1 Injection for Type 2 Diabetes & Cardiovascular Protection',
  'saxenda': 'Daily GLP-1 Agonist for Medical Weight Reduction',
  'dulaglutide': 'Type 2 Diabetes Once-Weekly Glycemic Regulation',
  'trulicity': 'Once-Weekly Subcutaneous GLP-1 Agonist for T2D Glycemic Control',
  'tirzepatide': 'Dual GIP/GLP-1 Agonist for Type 2 Diabetes & Weight Loss',
  'mounjaro': 'Dual Incretin Receptor Agonist for Powerful Glucose & Weight Reduction',
  'insulin': 'Type 1 & Advanced Type 2 Diabetes Absolute Glycemic Control',
  'lantus': 'Once-Daily Basal Insulin for 24-Hour Blood Sugar Stability',
  'humalog': 'Fast-Acting Mealtime Insulin for Postprandial Glucose Control',
  'novolog': 'Rapid-Acting Insulin Analog for Mealtime Coverage',
  'pantoprazole': 'Acid Reflux (GERD), Heartburn & Peptic Ulcers',
  'pan 40': 'Hyperacidity, Acid Reflux, Gastritis & Ulcer Healing',
  'pan d': 'Acid Reflux with Nausea, Vomiting & Gastric Fullness',
  'pan-d': 'Acid Reflux with Nausea, Vomiting & Gastric Fullness',
  'pantocid': 'Healing of Erosive Esophagitis & Gastric Acidity Relief',
  'protonix': 'Erosive Esophagitis & Pathologic Hypersecretory Gastric States',
  'omeprazole': 'Acid Reflux, Heartburn, Gastric Ulcers & H. Pylori Eradication',
  'omez': 'Acidity, GERD, Gastric Ulcers & Heartburn Relief',
  'omez d': 'Acidity, Gas & Nausea Associated with GERD',
  'prilosec': 'Frequent Heartburn & Gastroesophageal Reflux Disease (GERD)',
  'esomeprazole': 'Gastroesophageal Reflux Disease, Erosive Esophagitis & Ulcers',
  'nexpro': 'Erosive Gastritis, Heartburn & GERD Long-term Healing',
  'nexium': 'Healing of Erosive Esophagitis & Symptomatic GERD Treatment',
  'rabeprazole': 'Rapid Acidity Relief, Duodenal Ulcers & GERD',
  'razo': 'Rapid Relief from Acid Indigestion & Peptic Ulcers',
  'razo d': 'Acid Indigestion, Gas Fullness & Nausea Relief',
  'aciphex': 'Healing & Symptomatic Relief of Duodenal & Gastric Ulcers',
  'lansoprazole': 'Acid-Related Gastric Disorders, Heartburn & Peptic Ulcers',
  'prevacid': 'Treatment & Maintenance of Healed Erosive Esophagitis',
  'dexlansoprazole': 'Dual Delayed Release for 24-Hour Heartburn & GERD Control',
  'dexilant': 'Healing of All Grades of Erosive Esophagitis',
  'ranitidine': 'Gastric Acidity, Heartburn & Peptic Ulcer Healing',
  'rantac': 'Heartburn, Indigestion & Stomach Acidity Relief',
  'aciloc': 'Gastric Acid Reduction, Heartburn & GERD',
  'zantac': 'Short-term Relief of Heartburn & Acid Indigestion',
  'famotidine': 'Heartburn, Acid Indigestion, Sour Stomach & Peptic Ulcers',
  'pepcid': 'Prevention & Relief of Heartburn Associated with Acid Indigestion',
  'domperidone': 'Nausea, Vomiting, Gastric Fullness & Delayed Stomach Emptying',
  'motilium': 'Nausea, Vomiting, Epigastric Sense of Fullness & Reflux',
  'metoclopramide': 'Nausea, Vomiting, Diabetic Gastroparesis & Severe GERD',
  'reglan': 'Diabetic Gastroparesis & Symptomatic Gastroesophageal Reflux',
  'ondansetron': 'Nausea, Vomiting Prevention in Chemotherapy & Surgery',
  'zofran': 'Prevention of Nausea & Vomiting Caused by Chemotherapy or Surgery',
  'emeset': 'Nausea & Vomiting Relief in Acute Illness & Chemotherapy',
  'sucralfate': 'Gastric & Duodenal Mucosal Coating / Ulcer Protection',
  'sucrafil': 'Direct Protective Coating on Peptic Ulcer Craters',
  'digene': 'Instant Heartburn, Acidity, Gas & Stomach Discomfort Relief',
  'gelusil': 'Relief from Acidity, Gas, Heartburn & Bloated Stomach',
  'loperamide': 'Acute Diarrhea, Watery Loose Motions & Cramping',
  'imodium': 'Control & Symptomatic Relief of Acute & Chronic Diarrhea',
  'lactulose': 'Chronic Constipation & Hepatic Encephalopathy Toxin Removal',
  'duphalac': 'Gentle Colon-Cleansing Osmotic Stool Softening',
  'cremaffin': 'Gentle Overnight Relief from Constipation & Hard Stools',
  'dulcolax': 'Occasional Constipation & Bowel Evacuation',
  'bisacodyl': 'Short-term Relief of Constipation & Pre-Procedure Bowel Prep',
  'docusate': 'Stool Softener for Prevention of Straining During Defecation',
  'senna': 'Short-term Relief of Occasional Constipation',
  'senokot': 'Natural Vegetable Laxative for Gentle Overnight Constipation Relief',
  'ursodeoxycholic acid': 'Dissolution of Small Gallstones & Primary Biliary Cholangitis',
  'udiliv': 'Liver Protection, Bile Flow Enhancement & Gallstone Dissolution',
  'urso': 'Primary Biliary Cirrhosis / Cholangitis Treatment',
  'escitalopram': 'Depression, Major Depressive Disorder & Generalized Anxiety Disorder (GAD)',
  'nexito': 'Depression, Anxiety Disorders & Panic Attacks',
  'lexapro': 'Major Depressive Disorder & Generalized Anxiety Disorder',
  'sertraline': 'Depression, Panic Disorder, OCD, PTSD & Social Anxiety',
  'zosert': 'Depression, Obsessive-Compulsive Disorder & Panic Disorder',
  'zoloft': 'Depression, Panic Disorder, OCD, PTSD & Premenstrual Dysphoric Disorder',
  'fluoxetine': 'Depression, Bulimia Nervosa, OCD & Panic Disorder',
  'flunil': 'Major Depressive Episodes, Bulimia & Obsessive Thoughts',
  'prozac': 'Depression, Bulimia, OCD & Panic Disorder',
  'paroxetine': 'Major Depression, Panic Attacks, Social Anxiety & PTSD',
  'paxil': 'Major Depressive Disorder, Panic Disorder & GAD',
  'citalopram': 'Major Depressive Disorder & Mood Restoration',
  'celexa': 'Relief of Depressive Mood, Apathy & Loss of Interest',
  'fluvoxamine': 'Obsessive-Compulsive Disorder (OCD) & Social Anxiety',
  'luvox': 'Treatment of Obsessions & Compulsions in OCD',
  'venlafaxine': 'Depression, Generalized Anxiety, Social Phobia & Panic',
  'venlor': 'Depression, Chronic Anxiety & Panic Episodes',
  'effexor': 'Major Depressive Disorder & Generalized Anxiety Disorder',
  'effexor xr': 'Panic Disorder, Social Anxiety & Major Depression',
  'duloxetine': 'Depression, Diabetic Nerve Pain, Fibromyalgia & Anxiety',
  'dulane': 'Diabetic Neuropathic Pain, Depression & Chronic Musculoskeletal Pain',
  'cymbalta': 'Fibromyalgia, Chronic Musculoskeletal Pain & Depression',
  'mirtazapine': 'Major Depression with Insomnia & Appetite Loss',
  'mirtaz': 'Depressive Symptoms, Insomnia & Low Appetite',
  'remeron': 'Major Depressive Disorder with Sleep Disturbance',
  'bupropion': 'Depression, Seasonal Affective Disorder & Smoking Cessation',
  'wellbutrin': 'Major Depressive Disorder & Nicotine Withdrawal Aid',
  'trazodone': 'Major Depression, Anxiety & Chronic Severe Insomnia',
  'desyrel': 'Depression & Associated Sleep Maintenance Difficulties',
  'amitriptyline': 'Depression, Neuropathic Pain, Chronic Tension Headaches & Fibromyalgia',
  'elavil': 'Major Depressive Episodes & Chronic Nerve Pain',
  'tryptomer': 'Neuropathic Pain, Tension Headache Prevention & Sleep Support',
  'nortriptyline': 'Depression & Post-Herpetic Neuralgia Nerve Pain',
  'pamelor': 'Relief of Symptoms of Major Depressive Illness',
  'imipramine': 'Depression & Childhood Enuresis (Bedwetting)',
  'tofranil': 'Major Depressive Disorder & Nocturnal Enuresis in Children',
  'doxepin': 'Depression, Anxiety & Sleep Maintenance Insomnia',
  'clomipramine': 'Obsessive-Compulsive Disorder & Severe Phobias',
  'anafranil': 'Obsessions & Compulsions in Patients with OCD',
  'alprazolam': 'Panic Attacks, Severe Acute Anxiety & Agoraphobia',
  'alprax': 'Short-term Relief of Anxiety & Panic Disorder',
  'restyl': 'Acute Anxiety & Stress-Induced Nervousness',
  'xanax': 'Panic Disorder & Generalized Anxiety Symptoms',
  'clonazepam': 'Seizures, Panic Disorder, Agoraphobia & Akathisia',
  'clonafit': 'Panic Disorder, Seizure Control & Anxiety',
  'zapiz': 'Seizure Prophylaxis & Acute Panic Attacks',
  'klonopin': 'Seizure Disorders & Panic Disorder with or without Agoraphobia',
  'lorazepam': 'Severe Anxiety, Panic, Insomnia & Preoperative Sedation',
  'ativan': 'Short-term Management of Anxiety Disorders & Insomnia',
  'trapex': 'Severe Acute Anxiety, Agitation & Muscle Tension',
  'diazepam': 'Muscle Spasms, Severe Anxiety, Alcohol Withdrawal & Seizures',
  'valium': 'Acute Muscle Spasm, Alcohol Withdrawal Symptoms & Anxiety',
  'calmpose': 'Muscle Relaxation, Sedation & Acute Anxiety Relief',
  'zolpidem': 'Short-term Treatment of Insomnia & Sleep Initiation',
  'nitrest': 'Acute Insomnia & Sleep Maintenance Support',
  'ambien': 'Short-term Treatment of Difficulty with Sleep Onset',
  'zopiclone': 'Short-term Management of Insomnia',
  'eszopiclone': 'Difficulty Falling Asleep & Staying Asleep (Insomnia)',
  'lunesta': 'Longer-term Management of Transient & Chronic Insomnia',
  'melatonin': 'Circadian Rhythm Sleep Disorders & Jet Lag',
  'quetiapine': 'Bipolar Disorder, Schizophrenia & Treatment-Resistant Depression',
  'qutipin': 'Bipolar Mania, Schizophrenia & Adjunct in Major Depression',
  'seroquel': 'Schizophrenia, Bipolar Mania & Bipolar Depressive Episodes',
  'olanzapine': 'Schizophrenia & Bipolar I Disorder Manic Episodes',
  'olexar': 'Bipolar Disorder & Schizophrenic Symptoms',
  'zyprexa': 'Acute Agitation in Schizophrenia & Bipolar Disorder',
  'risperidone': 'Schizophrenia, Bipolar Mania & Irritability in Autism',
  'sizodon': 'Schizophrenia, Bipolar Episodes & Aggression',
  'risperdal': 'Schizophrenia & Acute Manic or Mixed Episodes in Bipolar I',
  'aripiprazole': 'Schizophrenia, Bipolar Disorder & Antidepressant Augmentation',
  'arizep': 'Schizophrenia, Manic Episodes & Major Depressive Augmentation',
  'abilify': 'Schizophrenia, Bipolar Mania & Major Depressive Disorder Add-on',
  'haloperidol': 'Acute Psychosis, Schizophrenia & Tourette Syndrome Tics',
  'haldol': 'Severe Psychomotor Agitation, Delirium & Chronic Schizophrenia',
  'clozapine': 'Treatment-Resistant Schizophrenia & Suicidal Behavior Reduction',
  'clozaril': 'Severely Ill Patients with Chronic Resistant Schizophrenia',
  'lithium': 'Bipolar Affective Disorder Mania & Maintenance Mood Stabilization',
  'gabapentin': 'Neuropathic Pain, Diabetic Nerve Pain & Partial Seizures',
  'gabaneuron': 'Diabetic Neuropathy, Nerve Pain & Burning Foot Pain',
  'neurontin': 'Postherpetic Neuralgia & Adjunctive Therapy in Partial Onset Seizures',
  'pregabalin': 'Diabetic Neuropathy, Fibromyalgia, Postherpetic Neuralgia & Spinal Cord Injury Pain',
  'pregalin': 'Peripheral Neuropathic Pain & Fibromyalgia Body Aches',
  'lyrica': 'Neuropathic Pain, Fibromyalgia & Generalized Anxiety',
  'levetiracetam': 'Partial Onset, Myoclonic & Tonic-Clonic Seizures (Epilepsy)',
  'levipil': 'Seizure Control in Epilepsy & Prevention of Convulsions',
  'keppra': 'Anticonvulsant for Partial, Myoclonic & Generalized Tonic-Clonic Seizures',
  'sodium valproate': 'Epilepsy, Absence Seizures, Bipolar Mania & Migraine Prevention',
  'valproate': 'Generalized Seizures, Bipolar Mania & Migraine Prevention',
  'encorate': 'Epileptic Convulsions & Bipolar Mood Stabilization',
  'depakote': 'Complex Partial Seizures, Bipolar Mania & Migraine Headaches',
  'carbamazepine': 'Partial Seizures, Generalized Tonic-Clonic Seizures & Trigeminal Neuralgia',
  'tegretol': 'Epilepsy Control & Severe Trigeminal Facial Nerve Pain',
  'mazetol': 'Trigeminal Neuralgia Electric Pain & Seizure Prevention',
  'phenytoin': 'Tonic-Clonic Seizures & Psychomotor Seizures',
  'eptoin': 'Epilepsy, Status Epilepticus & Grand Mal Convulsions',
  'dilantin': 'Control of Generalized Tonic-Clonic and Complex Partial Seizures',
  'lamotrigine': 'Epilepsy Seizures & Bipolar I Disorder Mood Episode Delay',
  'lamictal': 'Partial Seizures, Generalized Seizures & Bipolar Depression',
  'topiramate': 'Epilepsy Seizure Control & Chronic Migraine Prevention',
  'topamax': 'Partial Onset Seizures & Migraine Headache Prophylaxis',
  'donepezil': 'Alzheimer Disease Cognitive Decline & Dementia Symptoms',
  'aricept': 'Mild, Moderate, and Severe Dementia of the Alzheimer Type',
  'rivastigmine': 'Alzheimer Dementia & Parkinson Disease Dementia',
  'exelon': 'Mild to Moderate Dementia of Alzheimer or Parkinson Disease',
  'memantine': 'Moderate to Severe Alzheimer Disease Cognitive Protection',
  'namenda': 'Slowing Cognitive Decline in Moderate to Severe Alzheimer Disease',
  'levodopa': 'Parkinson Disease Motor Symptoms, Rigidity & Tremors',
  'carbidopa': 'Inhibitor of Extracerebral Decarboxylation for Parkinson Disease',
  'syndopa': 'Parkinson Disease Tremors, Slowness & Muscle Rigidity',
  'sinemet': 'Parkinsonian Rigidity, Akinesia, Tremor & Shuffling Gait',
  'pramipexole': 'Parkinson Disease Symptoms & Restless Legs Syndrome',
  'mirapex': 'Idiopathic Parkinson Disease & Moderate-to-Severe Restless Legs',
  'ropinirole': 'Parkinson Disease & Moderate to Severe Restless Legs Syndrome',
  'requip': 'Parkinson Disease Motor Symptoms & Restless Legs',
  'amantadine': 'Parkinson Disease Motor Fluctuations & Drug-Induced EPS',
  'trihexyphenidyl': 'Drug-Induced Parkinsonian Tremors & Rigidity',
  'pacitane': 'Parkinsonian Tremors & Antipsychotic-Induced Muscle Stiffness',
  'amoxicillin': 'Bacterial Ear, Nose, Throat, Skin & Chest Infections',
  'mox': 'Upper & Lower Respiratory Tract Bacterial Infections',
  'amoxil': 'Streptococcal Infections, Otitis Media & Sinusitis',
  'augmentin': 'Bacterial Respiratory Infections, Sinusitis, Dental Abscess & UTI',
  'augmentin 625': 'Bacterial Chest Infections, Sinusitis & Dental Abscess',
  'moxikind cv': 'Severe Bacterial Infections with Beta-Lactamase Resistance',
  'amoxyclav': 'Bronchitis, Pneumonia, Sinus Infection & Skin Infections',
  'ampicillin': 'Respiratory, GI, Urinary & Meningeal Bacterial Infections',
  'piperacillin': 'Severe Pseudomonas & Hospital-Acquired Gram-Negative Infections',
  'azithromycin': 'Bacterial Throat, Chest, Skin & Reproductive Infections',
  'azithral': 'Bacterial Tonsillitis, Sinusitis, Pneumonia & Bronchitis',
  'zithromax': 'Community-Acquired Pneumonia, Strep Throat & Chlamydia',
  'clarithromycin': 'H. Pylori Ulcer Infections & Respiratory Bacterial Infections',
  'biaxin': 'Pharyngitis, Tonsillitis, Acute Maxillary Sinusitis & Bronchitis',
  'ciprofloxacin': 'Urinary Tract Infections, Infectious Diarrhea & Bone Infections',
  'ciplox': 'Bacterial Eye, Ear, Urinary & Gastrointestinal Infections',
  'cipro': 'Complicated Urinary Tract Infections & Severe Bacterial Enteritis',
  'levofloxacin': 'Bacterial Sinusitis, Pneumonia, Kidney Infections & Chronic Bronchitis',
  'levomac': 'Bacterial Lung Infections, Sinusitis & Severe UTI',
  'levaquin': 'Pneumonia, Acute Sinusitis & Complicated Pyelonephritis',
  'ofloxacin': 'Bacterial Diarrhea, Typhoid Fever & Urinary Infections',
  'zenflox': 'Gastrointestinal Bacterial Diarrhea & Urinary Tract Infections',
  'oflox oz': 'Bacterial & Amoebic Mixed Dysentery with Stomach Cramping',
  'moxifloxacin': 'Acute Bacterial Sinusitis & Community-Acquired Pneumonia',
  'avelox': 'Complicated Skin Infections & Severe Bacterial Bronchitis',
  'cefixime': 'Typhoid Fever, Bacterial Urinary Infections & Throat Infections',
  'taxim o': 'Bacterial Chest Infections, Typhoid Fever & UTI',
  'suprax': 'Otitis Media, Pharyngitis, Tonsillitis & Uncomplicated UTI',
  'cefuroxime': 'Bacterial Pharyngitis, Sinusitis, Bronchitis & Lyme Disease',
  'cetil': 'Bacterial Tonsillitis, Bronchitis & Skin Tissue Infections',
  'ceftin': 'Pharyngitis, Tonsillitis, Acute Bacterial Otitis Media & Bronchitis',
  'cephalexin': 'Bacterial Skin Infections, Cellulitis & Urinary Infections',
  'keflex': 'Respiratory Tract, Otitis Media, Skin and Bone Infections',
  'ceftriaxone': 'Severe Meningitis, Sepsis, Pneumonia & Gonococcal Infections',
  'monocef': 'Severe Bacterial Sepsis, Meningitis & Post-Surgical Prophylaxis',
  'rocephin': 'Bacterial Meningitis, Intra-Abdominal Infections & Gonorrhea',
  'doxycycline': 'Acne, Chlamydia, Lyme Disease, Malaria Prevention & Respiratory Infections',
  'doxt': 'Severe Acne, Bacterial Chest Infections & Malaria Prophylaxis',
  'vibramycin': 'Rickettsial Infections, Chlamydia & Respiratory Tract Infections',
  'minocycline': 'Severe Inflammatory Acne Vulgaris & Bacterial Skin Lesions',
  'metronidazole': 'Amoebiasis, Giardiasis, Trichomoniasis & Anaerobic Infections',
  'flagyl': 'Intestinal Amoebic Dysentery & Anaerobic Bacterial Infections',
  'tinidazole': 'Amebiasis, Giardiasis & Trichomoniasis Parasitic Infections',
  'nitrofurantoin': 'Uncomplicated Urinary Tract Infections (Bladder Infection / Cystitis)',
  'martifur': 'Acute & Recurrent Bacterial Urinary Bladder Infections',
  'macrobid': 'Acute Uncomplicated Urinary Tract Infections (Cystitis)',
  'cotrimoxazole': 'Urinary Tract Infections, Pneumocystis Pneumonia & Bronchitis',
  'bactrim': 'Bacterial UTI, Shigellosis & Pneumocystis Jirovecii Prophylaxis',
  'septran': 'Bacterial Urinary, Respiratory & Intestinal Infections',
  'clindamycin': 'Dental Abscess, Bone Infections & Anaerobic Bacterial Infections',
  'dalacin c': 'Serious Anaerobic Infections, Dental Bone Infections & Deep Abscess',
  'cleocin': 'Serious Respiratory, Skin and Soft Tissue Anaerobic Infections',
  'fluconazole': 'Fungal Thrush, Vaginal Yeast Infections & Cryptococcal Meningitis',
  'forcan': 'Candidiasis, Fungal Ringworm & Systemic Fungal Infections',
  'diflucan': 'Vaginal Candidiasis, Oropharyngeal Thrush & Systemic Fungal Infection',
  'itraconazole': 'Systemic Fungal Nail Infections & Aspergillosis',
  'candiforce': 'Stubborn Fungal Skin Infections, Ringworm & Onychomycosis',
  'sporanox': 'Blastomycosis, Histoplasmosis & Onychomycosis of the Toenail',
  'terbinafine': 'Fungal Toenail Infections, Athlete’s Foot & Ringworm',
  'lamisil': 'Fungal Infections of the Skin and Nails (Onychomycosis)',
  'acyclovir': 'Herpes Simplex, Shingles (Herpes Zoster) & Chickenpox',
  'zovirax': 'Initial and Recurrent Mucocutaneous Herpes Simplex Infections',
  'valacyclovir': 'Herpes Zoster (Shingles), Genital Herpes & Cold Sores',
  'valtrex': 'Treatment of Herpes Zoster & Suppression of Recurrent Genital Herpes',
  'oseltamivir': 'Influenza A & B Flu Treatment and Post-Exposure Prophylaxis',
  'tamiflu': 'Treatment of Acute Uncomplicated Influenza in High-Risk Patients',
  'levothyroxine': 'Hypothyroidism (Underactive Thyroid Hormone Replacement)',
  'thyronorm': 'Underactive Thyroid (Hypothyroidism) Hormone Balance',
  'eltroxin': 'Thyroid Hormone Deficiency Replacement Therapy',
  'synthroid': 'Replacement Therapy in Congenital or Acquired Hypothyroidism',
  'euthyrox': 'Restoration of Normal Thyroid Hormone Levels',
  'liothyronine': 'Fast-acting T3 Replacement for Severe Hypothyroidism / Myxedema',
  'cytomel': 'Hypothyroidism & Pituitary TSH Suppression',
  'carbimazole': 'Hyperthyroidism (Overactive Thyroid Excess Production)',
  'neo mercazole': 'Overactive Thyroid & Preparation for Thyroidectomy',
  'methimazole': 'Hyperthyroidism & Preparation for Radioactive Iodine Therapy',
  'tapazole': 'Medical Management of Hyperthyroidism in Patients with Graves Disease',
  'propylthiouracil': 'Hyperthyroidism & Thyroid Storm Crisis',
  'cabergoline': 'Hyperprolactinemia (High Prolactin Tumors / Galactorrhea)',
  'dostinex': 'Inhibition of Physiological Lactation & Hyperprolactinemic Disorders',
  'finasteride': 'Benign Prostatic Hyperplasia (Enlarged Prostate) & Male Pattern Hair Loss',
  'proscar': 'Reduction in the Risk of Acute Urinary Retention in BPH',
  'propecia': 'Male Pattern Hair Loss (Androgenetic Alopecia) on Vertex',
  'dutasteride': 'Benign Prostatic Hyperplasia Symptom Relief & Prostate Shrinkage',
  'avodart': 'Enlarged Prostate Urinary Flow Improvement & Surgery Risk Reduction',
  'tamsulosin': 'Enlarged Prostate (BPH) Urinary Hesitancy & Flow Improvement',
  'urimax': 'Enlarged Prostate (BPH) Urinary Hesitancy & Easy Urination',
  'flomax': 'Benign Prostatic Hyperplasia Difficulty Urinating Relief',
  'alfuzosin': 'Lower Urinary Tract Symptoms Associated with BPH',
  'uroxatral': 'Urinary Flow Obstruction Relief from Enlarged Prostate',
  'silodosin': 'Benign Prostatic Hyperplasia Hesitancy & Weak Stream Relief',
  'silodal': 'Enlarged Prostate Urinary Hesitancy & Nocturia Relief',
  'rapaflo': 'Signs and Symptoms of Benign Prostatic Hyperplasia',
  'sildenafil': 'Erectile Dysfunction & Pulmonary Arterial Hypertension',
  'viagra': 'Erectile Dysfunction (Male Impotence) Treatment',
  'revatio': 'Pulmonary Arterial Hypertension Exercise Capacity Improvement',
  'tadalafil': 'Erectile Dysfunction & Benign Prostatic Hyperplasia (BPH)',
  'cialis': 'Erectile Dysfunction & Lower Urinary Tract Symptoms of BPH',
  'vardenafil': 'Erectile Dysfunction Treatment',
  'levitra': 'Male Sexual Function Enhancement & Impotence Relief',
  'oxybutynin': 'Overactive Bladder, Urinary Urgency & Incontinence Leakage',
  'ditropan': 'Bladder Instability Associated with Incontinence',
  'tolterodine': 'Overactive Bladder with Symptoms of Frequency, Urgency & Leakage',
  'detrol': 'Overactive Bladder Urinary Incontinence Reduction',
  'solifenacin': 'Overactive Bladder Urge Incontinence & Frequency',
  'vesicare': 'Urinary Urgency, Frequency and Urge Incontinence in OAB',
  'cholecalciferol': 'Vitamin D Deficiency, Calcium Absorption & Bone Health',
  'vitamin d3': 'Bone Density Maintenance & Immune System Support',
  'calcirol': 'Severe Vitamin D Deficiency & Osteomalacia Prevention',
  'd rise': 'High-Dose Weekly Vitamin D3 Replenishment',
  'calcitriol': 'Active Vitamin D for Renal Osteodystrophy & Hypocalcemia',
  'rocaltrol': 'Management of Hypocalcemia in Dialysis Patients',
  'calcium carbonate': 'Calcium Supplementation for Strong Bones & Teeth',
  'shelcal': 'Calcium & Vitamin D3 Deficiency in Osteoporosis',
  'cipcal': 'Bone Mineralization & Pregnancy Calcium Support',
  'methylcobalamin': 'Vitamin B12 Deficiency, Nerve Repair & Diabetic Neuropathy',
  'neurobion': 'Vitamin B-Complex for Nerve Health & Numbness Relief',
  'neurobion forte': 'Nerve Regeneration, Vitamin B Deficiency & Paresthesia Relief',
  'cyanocobalamin': 'Pernicious Anemia & Vitamin B12 Deficiency',
  'folic acid': 'Folate Deficiency Anemia, Red Blood Cell Production & Prenatal Support',
  'folvite': 'Folic Acid Supplementation in Pregnancy & Anemia Prevention',
  'ferrous sulfate': 'Iron-Deficiency Anemia Treatment & Red Blood Cell Formation',
  'slow fe': 'Iron Deficiency & Iron-Deficiency Anemia with Gentle GI Release',
  'ferrous ascorbate': 'Iron-Deficiency Anemia with Enhanced Vitamin C Absorption',
  'orofer': 'Rapid Hemoglobin Elevation & Iron Storage Replenishment',
  'zincovit': 'Multivitamin & Zinc Formula for Immune Function & Convalescence',
  'becosules': 'Vitamin B-Complex with Vitamin C for Mouth Ulcers & Stamina',
  'supradyn': 'Daily Multivitamin & Multimineral for Vitality & Energy',
  'potassium chloride': 'Hypokalemia (Low Blood Potassium from Diuretics)',
  'potclor': 'Potassium Supplement for Preventing Electrolyte Imbalance',
  'k dur': 'Extended-Release Potassium Chloride for Kaliuresis Prevention',
  'magnesium oxide': 'Magnesium Deficiency & Acid Indigestion',
  'coenzyme q10': 'Cellular Energy Production, Heart Health & Statin Myopathy Protection',
  'coq10': 'Cardiovascular Support & Mitochondrial Antioxidant Protection',
  'omega 3': 'Cardiovascular Health, Triglyceride Reduction & Brain Wellness',
  'fish oil': 'Reduction of High Blood Triglycerides & Joint Mobility Support',
  'ashwagandha': 'Stress Reduction, Vitality, Cognitive Health & Immunity',
  'withania somnifera': 'Adaptogen for Cortisol Reduction, Stamina & Mental Calm',
  'turmeric': 'Joint Inflammation, Antioxidant Support & General Wellness',
  'curcumin': 'Potent Anti-inflammatory, Joint Comfort & Cellular Protection',
  'tulsi': 'Respiratory Health, Immune Support & Adaptogenic Stress Relief',
  'holy basil': 'Immunity Booster, Cough Relief & Environmental Stress Protection',
  'brahmi': 'Memory Retention, Cognitive Focus & Mental Clarity',
  'bacopa monnieri': 'Nootropic Support for Brain Function & Nervous System Calm',
  'triphala': 'Digestive Regularity, Gut Cleansing & Gentle Detoxification',
  'guggul': 'Lipid Balance, Joint Comfort & Healthy Metabolic Function',
  'shatavari': 'Female Hormonal Balance, Reproductive Vitality & Lactation Support',
  'amla': 'High Natural Vitamin C, Immunity & Antioxidant Hair/Skin Health',
  'neem': 'Blood Purification, Clear Skin & Antimicrobial Defense',
  'karela': 'Natural Blood Glucose Regulation & Metabolic Support',
  'bitter melon': 'Support for Healthy Blood Sugar & Pancreatic Function',
  'giloy': 'Immunity Modulation, Chronic Fever Recovery & Detoxification',
  'tinospora cordifolia': 'Platelet Count Support & Systemic Immunity Enhancement',
  'moringa': 'Nutrient-Dense Superfood for Energy, Minerals & Antioxidants',
  'spirulina': 'Superfood Protein, Micronutrient Balance & Stamina',
  'chyawanprash': 'Traditional Ayurvedic Immune Rejuvenation & Vitality Paste',
  'liv 52': 'Hepatic Cell Protection, Liver Toxin Defense & Appetite Support',
  'septilin': 'Immune Defense Against Recurrent Respiratory Infections',
  'rumalaya': 'Ayurvedic Joint Comfort, Mobility & Musculoskeletal Relief',
  'cystone': 'Kidney Health, Urinary Tract Comfort & Stone Prevention',
  'geriforte': 'Antioxidant Rejuvenator & Geriatric Physical Wellness',
  'ginkgo biloba': 'Cognitive Health, Memory Function & Peripheral Circulation',
  'st johns wort': 'Mild to Moderate Depressive Mood & Nervous Tension',
  'garlic extract': 'Circulatory Support & Mild Blood Pressure Regulation',
  'ginseng': 'Physical Endurance, Mental Alertness & Vitality Enhancement',
  'ginger extract': 'Nausea Relief, Digestive Comfort & Anti-inflammatory Support',
  'licorice root': 'Gastric Soothing, Throat Comfort & Adrenal Balance',
  'kava kava': 'Anxiety Relief, Emotional Relaxation & Stress Alleviation',
  'valerian root': 'Restful Sleep Initiation & Nighttime Muscle Relaxation',
  'green tea extract': 'Antioxidant Defense & Metabolic Energy Support',
  'milk thistle': 'Silymarin Liver Cell Protection & Toxin Defense',
};

// ─── Chemical Salt & Generic Pattern Heuristics ──────────────────────────────
export const CHEMICAL_SALT_INDICATIONS = [
  {
    pattern: /levocetirizine.*montelukast|montelukast.*levocetirizine/i,
    indication: 'Allergic Rhinitis, Sneezing, Runny Nose, Watery Eyes & Allergic Asthma',
  },
  {
    pattern: /paracetamol.*ibuprofen|ibuprofen.*paracetamol/i,
    indication: 'Severe Musculoskeletal Pain, Joint Inflammation & Fever Relief',
  },
  {
    pattern: /paracetamol.*aceclofenac|aceclofenac.*paracetamol/i,
    indication: 'Acute Joint Pain, Backache, Dental Pain & Inflammation',
  },
  {
    pattern: /aceclofenac.*paracetamol.*serratiopeptidase/i,
    indication: 'Severe Inflammatory Swelling, Post-Traumatic Edema & Pain Relief',
  },
  {
    pattern: /pantoprazole.*domperidone|domperidone.*pantoprazole/i,
    indication: 'Acid Reflux (GERD) with Nausea, Vomiting & Gastric Fullness',
  },
  {
    pattern: /rabeprazole.*domperidone|domperidone.*rabeprazole/i,
    indication: 'Acid Indigestion, Heartburn, Gas Fullness & Nausea Relief',
  },
  {
    pattern: /naproxen.*domperidone/i,
    indication: 'Acute Migraine Headache with Nausea & Vomiting Prevention',
  },
  {
    pattern: /telmisartan.*hydrochlorothiazide|telmisartan.*amlodipine/i,
    indication: 'High Blood Pressure (Dual Therapy for Resistant Hypertension)',
  },
  {
    pattern: /glimepiride.*metformin|metformin.*glimepiride/i,
    indication: 'Type 2 Diabetes Mellitus (Dual Therapy Blood Sugar Control)',
  },
  {
    pattern: /vildagliptin.*metformin|sitagliptin.*metformin/i,
    indication: 'Type 2 Diabetes Mellitus Fasting & Post-Meal Sugar Regulation',
  },
  {
    pattern: /amoxicillin.*clavulan/i,
    indication: 'Bacterial Chest Infections, Sinusitis, Dental Abscess & UTI',
  },
  {
    pattern: /levothyroxine/i,
    indication: 'Hypothyroidism (Underactive Thyroid Hormone Replacement)',
  },
  {
    pattern: /ondansetron/i,
    indication: 'Nausea, Vomiting & Motion Sickness Relief',
  },
  {
    pattern: /loperamide/i,
    indication: 'Acute Diarrhea, Watery Loose Motions & Cramping',
  },
  {
    pattern: /cholecalciferol|vitamin d3/i,
    indication: 'Vitamin D Deficiency, Calcium Absorption & Bone Health',
  },
  {
    pattern: /folic acid/i,
    indication: 'Folate Deficiency Anemia, Red Blood Cell Production & Prenatal Support',
  },
  {
    pattern: /curcumin|turmeric/i,
    indication: 'Joint Inflammation, Antioxidant Support & General Wellness',
  },
  {
    pattern: /ashwagandha/i,
    indication: 'Stress Reduction, Vitality, Cognitive Health & Immunity',
  },
  {
    pattern: /ginkgo/i,
    indication: 'Cognitive Health, Memory Function & Peripheral Circulation',
  },
];

// ─── Suffix / Root Class Heuristics ───────────────────────────────────────────
const SUFFIX_INDICATIONS = [
  { test: (s) => /statin$/i.test(s), text: 'High Cholesterol (Hyperlipidemia) & Cardiovascular Protection' },
  { test: (s) => /pril$/i.test(s), text: 'High Blood Pressure (Hypertension) & Heart Failure Management' },
  { test: (s) => /sartan$/i.test(s), text: 'High Blood Pressure (Hypertension) & Cardiovascular Protection' },
  { test: (s) => /olol$/i.test(s), text: 'High Blood Pressure, Angina & Heart Rate Regulation' },
  { test: (s) => /dipine$/i.test(s), text: 'High Blood Pressure (Hypertension) & Angina (Chest Pain)' },
  { test: (s) => /prazole$/i.test(s), text: 'Acid Reflux (GERD), Heartburn & Peptic Ulcers' },
  { test: (s) => /tidine$/i.test(s), text: 'Gastric Acidity, Heartburn & Acid Reflux' },
  { test: (s) => /gliflozin$/i.test(s), text: 'Type 2 Diabetes Mellitus, Heart Failure & Kidney Protection' },
  { test: (s) => /gliptin$/i.test(s), text: 'Type 2 Diabetes Mellitus & Blood Glucose Regulation' },
  { test: (s) => /tinib$/i.test(s), text: 'Autoimmune Inflammatory Disorders & Arthritis' },
  { test: (s) => /mab$/i.test(s), text: 'Targeted Immunotherapy & Autoimmune Conditions' },
  { test: (s) => /cillin$/i.test(s), text: 'Bacterial Infections Treatment' },
  { test: (s) => /mycin$/i.test(s), text: 'Bacterial Respiratory, Skin & Soft Tissue Infections' },
  { test: (s) => /cycline$/i.test(s), text: 'Bacterial Infections, Acne & Respiratory Infections' },
  { test: (s) => /floxacin$/i.test(s), text: 'Bacterial Infections, UTI & Gastrointestinal Infections' },
  { test: (s) => /zole$/i.test(s), text: 'Fungal or Parasitic Infection Treatment' },
  { test: (s) => /triptan$/i.test(s), text: 'Acute Migraine Attack & Severe Throbbing Headaches' },
  { test: (s) => /terol$/i.test(s), text: 'Asthma, Wheezing & Bronchial Airway Obstruction' },
  { test: (s) => /profen|fenac|coxib$/i.test(s), text: 'Pain Relief, Joint Inflammation, Arthritis & Musculoskeletal Aches' },
];

/**
 * getMedicineIndication(medOrName)
 * ─────────────────────────────────────────────────────────────────────────────
 * Primary public utility to resolve "What this medicine is used for / which issue".
 *
 * @param {Object|string} medOrName - Medication object or medicine name string
 * @returns {string} Human-friendly clinical condition or indication
 */
export function getMedicineIndication(medOrName) {
  if (!medOrName) return 'Prescribed Medical Treatment';

  const med = typeof medOrName === 'string' ? { name: medOrName } : medOrName;

  // 1. Direct explicit purpose or indication from database/backend
  if (med.purpose && typeof med.purpose === 'string' && med.purpose.trim().length > 3) {
    return med.purpose.trim();
  }
  if (med.indication && typeof med.indication === 'string' && med.indication.trim().length > 3) {
    return med.indication.trim();
  }

  const rawName = String(med.name || '').toLowerCase().trim();
  const rawGeneric = String(med.generic || '').toLowerCase().trim();
  const rawDosage = String(med.dosage || '').toLowerCase();
  const rawCategory = String(med.category || '').toLowerCase();

  // Extract cleaned brand key (e.g., "Xyzal M" -> "xyzal m" or "xyzal")
  const cleanedName = rawName
    .replace(/\s+\d+(\.\d+)?\s*(mg|mcg|g|ml|iu)?$/i, '')
    .trim();

  // Extract salts from dosage string if present: "salts: levocetirizine dihydrochloride + montelukast sodium"
  let saltsText = '';
  if (rawDosage.includes('salts:')) {
    const parts = rawDosage.split('•');
    const saltPart = parts.find((p) => p.includes('salts:'));
    if (saltPart) {
      saltsText = saltPart.replace('salts:', '').trim();
    }
  }

  const combinedSearchText = `${rawName} ${cleanedName} ${rawGeneric} ${saltsText} ${rawDosage}`.toLowerCase();

  // 2. Direct dictionary lookup by exact cleaned name or brand key
  if (MEDICINE_INDICATIONS[cleanedName]) {
    return MEDICINE_INDICATIONS[cleanedName];
  }
  if (MEDICINE_INDICATIONS[rawName]) {
    return MEDICINE_INDICATIONS[rawName];
  }

  // 3. Substring match across dictionary keys (e.g. "xyzal", "naxdom", "dolo", "pan-d")
  for (const [key, indication] of Object.entries(MEDICINE_INDICATIONS)) {
    if (key.length >= 4 && (rawName.includes(key) || cleanedName.includes(key))) {
      return indication;
    }
  }

  // 4. Chemical salt and active formulation pattern matching
  for (const item of CHEMICAL_SALT_INDICATIONS) {
    if (item.pattern.test(combinedSearchText)) {
      return item.indication;
    }
  }

  // 5. Chemical drug suffix / stem matching
  const words = `${cleanedName} ${rawGeneric}`.split(/\s+/).filter(Boolean);
  for (const word of words) {
    const cleanWord = word.replace(/[^a-z]/gi, '');
    for (const rule of SUFFIX_INDICATIONS) {
      if (rule.test(cleanWord)) {
        return rule.text;
      }
    }
  }

  // 6. Clinical category heuristics
  if (rawCategory.includes('antihypertensive') || rawCategory.includes('blood pressure')) {
    return 'High Blood Pressure (Hypertension) & Cardiovascular Health';
  }
  if (rawCategory.includes('antidiabetic') || rawCategory.includes('diabetes')) {
    return 'Type 2 Diabetes Mellitus & Blood Glucose Regulation';
  }
  if (rawCategory.includes('anticoagulant')) {
    return 'Blood Clot Prevention & Anticoagulation Therapy';
  }
  if (rawCategory.includes('antiplatelet')) {
    return 'Blood Thinner, Heart Attack & Stroke Prevention';
  }
  if (rawCategory.includes('analgesic') || rawCategory.includes('nsaid') || rawCategory.includes('pain')) {
    return 'Pain Relief, Fever & Inflammation Management';
  }
  if (rawCategory.includes('ppi') || rawCategory.includes('antacid') || rawCategory.includes('gerd')) {
    return 'Acid Reflux (GERD), Heartburn & Peptic Ulcers';
  }
  if (rawCategory.includes('antibiotic')) {
    return 'Bacterial Infections Treatment';
  }
  if (rawCategory.includes('antihistamine') || rawCategory.includes('allergy')) {
    return 'Allergic Rhinitis, Sneezing, Runny Nose & Itching';
  }
  if (rawCategory.includes('statin') || rawCategory.includes('cholesterol')) {
    return 'High Cholesterol & Cardiovascular Protection';
  }
  if (rawCategory.includes('supplement') || rawCategory.includes('vitamin') || rawCategory.includes('mineral')) {
    return 'Nutritional Supplementation & General Wellness';
  }
  if (med.type === 'HERBAL') {
    return 'Herbal Wellness & Natural Therapeutic Support';
  }

  return 'Prescribed Medical Treatment';
}
